variable "env" {}
variable "instance_type" {}
variable "zone_id" {}
variable "vault_token" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr_block" {}
variable "vpc_cidr_block" {}
variable "default_route_table_id" {}
variable "frontend_subnets" {}
variable "availability_zones" {}
variable "backend_subnets" {}
variable "db_subnets" {}
variable "public_subnets" {}
variable "bastion_nodes" {}
variable "prometheus_nodes" {}
variable "kms_key_id" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_capacity" {}